# Generated by Django 5.2.7 on 2025-10-28 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linefree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='linefree.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('organization', 'name')},
        ),
    ]
